### PR TITLE
Generate formspecs on interact, not on update

### LINKED ISSUE #39: formspec in meta -> use show formspec and generate dynamically
formspecs in meta are really a bad idea and should be replaced. creating this issue for the record as it has been touch upon in other issues/prs

### PR DESCRIPTION
**Pull request by oversword**
Fixes #39 

This is based on https://github.com/mt-mods/travelnet/pull/44/files to avoid duplicating work

- `update_formspec` and `reset_formspec` deprecated as they would only update metadata
- Uses same behaviour on punch and right click - no need to act differently anymore
- Move "Move Up" and "Move Down" behaviour out of `primary_formspec` to its own function

### CODE REVIEW

**Comment by oversword** [comment]
I feel like I'm re-arranging dead bodies to try and get rid of the smell on this one - I really need to redo the way formspecs work entirely. This work is still required, and is a good first step, but it once again highlights how bad the formspecs situation is in this mod.

**Comment by oversword** [comment]
I'm thinking we should add an LBM to remove metadata formspecs, currently the old formspec will flash up briefly on an old travelnet

**Comment by wsor4035** [comment]
it doesnt seem worth the overhead to use a lbm, just check for formspec meta on rightclick and nuke it if its there

**Comment by oversword** [comment]
> it doesnt seem worth the overhead to use a lbm, just check for formspec meta on rightclick and nuke it if its there

Yeah I think that's better, especially because I can't get a complete list of travelnets at the right time (because they can be registered after the mod loads), would mean registering a new LBM for each or doing it on a `minetest.after`... not sure that's even possible for registering an LBM. Either way, much easier to do it on interact, it's just one extra call to the metadata.

**Review by BuckarooBanzay — APPROVED** [review]

**Review by S-S-X — APPROVED** [review]
As a concept this is way better, there's one downside which is slower response which however mostly affects players if when server is lagging badly or player connection is unstable / very slow.
On the other hand it also reduces network traffic a bit simply because metadata footprint is smaller and players will only download travelnet formspecs they're actually using and only when they're using it.

(also, did not test but looks fine)

**Review by wsor4035 — APPROVED** [review]

**Comment by oversword** [comment]
@S-S-X The only thing in there which might be a little slow is that we have to sort the networks into the right order each time the forms is rendered - frankly I don't like the way the order is maintained anyway, it should have just been stored as an ordered list.

Perhaps we can cache the order of the stations somewhere to avoid doing this every time, apart from that the form render is just basic string compilation, nothing extraordinary.

**Comment by oversword** [comment]
I know, I understand the problem, but I guess you're saying it's mainly other things that will cause delay, not the generation of this forms itself. I just mean making this as fast as possible is going to help get it there sooner.

**Pull request merged**
