### PR TITLE
add fr, it and pl translations, also some updates/fixes

### PR DESCRIPTION
**Pull request by waxtatect**
_i'd say it took longer than i thought_

Each commit title and description detail the changes<del>, i'd just add, the descriptions (https://github.com/mt-mods/travelnet/blob/master/functions.lua#L22) aren't in the template but translated through S(description) in https://github.com/mt-mods/travelnet/commit/b64675a30222ef82ac483850a9fd4ee6979ea799, maybe add S() individually so the script find them?</del>

edit: first commit translations are from Sokomine's repo, why it added mt-mods... hmm
editedit: (not related to the content of this PR), i noticed this function is not called anywhere: https://github.com/mt-mods/travelnet/blob/20e77d56ef66f12e823c6379f9bf7d1cafa1142b/functions.lua#L354

### CODE REVIEW

**Review by wsor4035 — DISMISSED** [review]
note, someone else should look over the wording changes here(before merging), but still works, and the langauges shoved throw google translate look roughly correct, so unless someone more knowledgeable can point out where i missed something, approving

**Comment by wsor4035** [comment]
hold the phone, it looks like according to https://github.com/Sokomine/travelnet/pull/52#issuecomment-566036904 this has already been handled here,

**Comment by waxtatect** [comment]
unless requested, i won't commit anymore to this PR
please consider merging

**Review by wsor4035 — APPROVED** [review]

**Comment by wsor4035** [comment]
not sure why actions is acting up.... anyways, once that is happy, ill merge

**Pull request merged**
