### PR TITLE
List all craftable items and recipes in README

### PR DESCRIPTION
**Pull request by cweiske**

### CODE REVIEW

**Review by wsor4035 — CHANGES_REQUESTED** [review]
this probably should be in a separate file, like the settings are linked to. dont want the readme to become a book over time

**Comment by cweiske** [comment]
I've moved the items list to `doc/crafting.md` and linked that file from the readme.

About coloring - I would love to see docs about this since I don't know how I can use it myself.

**Comment by cweiske** [comment]
The good thing about the readme becoming large is that all information would be available on the [contentdb page](https://content.minetest.net/packages/mt-mods/travelnet/). Many contentdb entries lack explanation.

I love large readmes :)

**Comment by wsor4035** [comment]
> The good thing about the readme becoming large is that all information would be available on the [contentdb page](https://content.minetest.net/packages/mt-mods/travelnet/). Many contentdb entries lack explanation.
> 
> I love large readmes :)

Iirc this is incorrect, Readme is only imported on package creation

**Review by wsor4035 — APPROVED** [review]

**Pull request merged**
